apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onim.fullname" . }}
  labels:
    app: {{ include "onim.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "onim.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onim.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: USER_NAME
              value: "{{ .Values.onimApp.user }}"
            - name: PASSWORD
              value: "{{ .Values.onimApp.password }}"