replicaCount: 3

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"


pass: ".ultpAss1234"
user: "defaultuser"
Acredentials: "test@A4"
Dbpassword: "password"


service:
  type: ClusterIP
  port: 80