replicaCount: 3

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

onimApp:
  password: "defaultpass1234"
  user: "defaultuser"

service:
  type: ClusterIP
  port: 80